# Generated by Django 3.0.3 on 2020-03-27 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negociospush', '0002_auto_20200309_1046'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='process',
            name='ProcessType',
        ),
        migrations.AddField(
            model_name='process',
            name='ProcessStateName',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='process',
            name='Amount',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='process',
            name='ClassCode',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='process',
            name='ContractType',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='process',
            name='DefinitiveAmount',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='process',
            name='Description',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='process',
            name='EntityCode',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='process',
            name='EntityNIT',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='process',
            name='EntityName',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='process',
            name='ExecutionCity',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='process',
            name='FamilyCode',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='process',
            name='IdProcessType',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='process',
            name='LoadDate',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='process',
            name='ProcessNumber',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='process',
            name='ProcessState',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='process',
            name='ProcessTypeName',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='process',
            name='SegmentCode',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='process',
            name='SystemLoadDate',
            field=models.DateTimeField(null=True),
        ),
    ]
