# Generated by Django 3.0.3 on 2020-03-27 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negociospush', '0003_auto_20200326_1956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process',
            name='Amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='process',
            name='ClassCode',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='process',
            name='ContractType',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='process',
            name='EntityCode',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='process',
            name='EntityNIT',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='process',
            name='EntityName',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='process',
            name='ExecutionCity',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='process',
            name='FamilyCode',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='process',
            name='LoadDate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='process',
            name='ProcessNumber',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='process',
            name='ProcessState',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='process',
            name='ProcessStateName',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='process',
            name='ProcessTypeName',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='process',
            name='SegmentCode',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='process',
            name='SystemLoadDate',
            field=models.DateTimeField(),
        ),
    ]
