# Generated by Django 3.0.3 on 2020-03-27 06:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negociospush', '0005_auto_20200327_0046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process',
            name='SystemLoadDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
