# Generated by Django 3.0.3 on 2020-04-03 05:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negociospush', '0006_auto_20200327_0111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process',
            name='Amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='process',
            name='ClassCode',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='process',
            name='ContractType',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='process',
            name='Description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='process',
            name='EntityCode',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='process',
            name='EntityNIT',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='process',
            name='EntityName',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='process',
            name='ExecutionCity',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='process',
            name='FamilyCode',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='process',
            name='LoadDate',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='process',
            name='ProcessState',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='process',
            name='ProcessStateName',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='process',
            name='ProcessTypeName',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='process',
            name='SegmentCode',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='process',
            name='SystemLoadDate',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
