# Generated by Django 3.0.3 on 2020-04-03 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negociospush', '0007_auto_20200403_0059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process',
            name='ExecutionCity',
            field=models.TextField(null=True),
        ),
    ]
