# Generated by Django 3.0.3 on 2020-04-12 06:06

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('negociospush', '0009_code'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Code',
            new_name='UserCode',
        ),
    ]
