# Generated by Django 3.0.3 on 2020-04-12 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('negociospush', '0010_auto_20200412_0106'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserCode',
        ),
    ]
