# Generated by Django 3.0.3 on 2020-04-13 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negociospush', '0013_notification_notificationprocesses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process',
            name='EntityNIT',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
