# Generated by Django 3.0.3 on 2020-04-13 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('negociospush', '0015_remove_notification_process'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NotificationProcesses',
        ),
    ]
