# Generated by Django 3.0.3 on 2020-04-13 06:29

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('negociospush', '0016_delete_notificationprocesses'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationProcesses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SystemLoadDate', models.DateTimeField(default=datetime.datetime.now)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='negociospush.Notification')),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='negociospush.Process')),
            ],
        ),
    ]
