# Generated by Django 3.0.3 on 2020-05-03 01:14

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('negociospush', '0017_notificationprocesses'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventTypes',
            fields=[
                ('IdType', models.AutoField(primary_key=True, serialize=False)),
                ('EventName', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('IdEvent', models.AutoField(primary_key=True, serialize=False)),
                ('Data', models.TextField()),
                ('Timestamp', models.DateTimeField(default=datetime.datetime.now)),
                ('EventType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='negociospush.EventTypes')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
