# Generated by Django 3.0.3 on 2020-03-09 04:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Process',
            fields=[
                ('IdProcess', models.AutoField(primary_key=True, serialize=False)),
                ('EntityCode', models.IntegerField()),
                ('EntityName', models.CharField(max_length=255)),
                ('EntityNIT', models.CharField(max_length=15)),
                ('ProcessType', models.IntegerField()),
                ('ProcessNumber', models.IntegerField()),
                ('ProcessState', models.IntegerField()),
                ('ExecutionCity', models.CharField(max_length=255)),
                ('IdProcessType', models.IntegerField()),
                ('ProcessTypeName', models.CharField(max_length=255)),
                ('SegmentCode', models.IntegerField()),
                ('FamilyCode', models.IntegerField()),
                ('ClassCode', models.IntegerField()),
                ('Description', models.CharField(max_length=255)),
                ('ContractType', models.CharField(max_length=255)),
                ('LoadDate', models.DateField()),
                ('SystemLoadDate', models.DateTimeField()),
                ('Amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('DefinitiveAmount', models.DecimalField(decimal_places=2, max_digits=20)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('SegmentCode', models.IntegerField()),
                ('SegmentName', models.CharField(max_length=255)),
                ('FamilyCode', models.IntegerField()),
                ('FamilyName', models.CharField(max_length=255)),
                ('ClassCode', models.IntegerField()),
                ('ClassName', models.CharField(max_length=255)),
                ('ProductCode', models.IntegerField(primary_key=True, serialize=False)),
                ('ProductName', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('IdProfile', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('productCode', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='negociospush.Product')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
